version: "3.8"

services:
  sow-generator:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html/:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sow-generator.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.sow-generator.entrypoints=websecure"
      - "traefik.http.routers.sow-generator.tls.certresolver=letsencrypt"
